let bool = true;
const string = "forty two";
let integer = 42;
const this_is_null = null;
let float = 42.42;
displayThisText(bool);
displayThisText(string);
displayThisText(integer);
displayThisText(float);
displayThisText(this_is_null);
